name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Copy env files from client config folder
      run: cp -rf /var/www/client/.* /var/www/yemsay/_work/yemsays-app/yemsays-app

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: |
        export NODE_OPTIONS="--max_old_space_size=8096"
        CI=false npm run build --if-present

    - name: Reload server instances
      run: pm2 reload yemsay-client --update-env --wait-ready
    
    - name: Check if job failed or push not merged
      if: always() 
      run: |
        if [ "${{ job.status }}" != "success" ] || [ "${{ github.event_name }}" == "pull_request" ]; then
          pm2 rollback
        fi