name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cp -rf /var/www/config-client* /var/www/config-client.* /var/www/yemsay/_work/yemsays-app/yemsays-app
    - run: npm install
    - run: |
        export NODE_OPTIONS="--max_old_space_size=8096"
        CI=false npm run build --if-present

    # - run: pm2 stop 3
    # - run: pm2 start 3
    # - run: pm2 save